"""Agregar completed_at

Revision ID: 5d656ce105bc
Revises: c9e078956131
Create Date: 2025-05-25 17:35:32.270772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d656ce105bc"
down_revision: Union[str, None] = "c9e078956131"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "appointments", sa.Column("completed_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "appointments", sa.Column("completed_at", sa.DateTime(), nullable=True)
    )
    op.execute("""
        ALTER TABLE appointments
        MODIFY update_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("appointments", "completed_at")
    # ### end Alembic commands ###
