"""Cambiar datos para autocompletar fechas

Revision ID: c9e078956131
Revises: 
Create Date: 2025-05-25 17:28:21.784865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c9e078956131'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_google_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('picture_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('appointments', 'user_google_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_appointments_create_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_datetime'), table_name='appointments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointments_datetime'), 'appointments', ['update_at'], unique=False)
    op.create_index(op.f('ix_appointments_create_at'), 'appointments', ['create_at'], unique=False)
    op.alter_column('appointments', 'user_google_id',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
